name: CI/CD Pipeline

concurrency: ci-healthfrontend-${{ github.ref }}

env:
  TF_VERSION: '1.1.5'
  TF_WORKING_DIR: 'terraform'
  IMAGE_TAG: ${{ github.sha }}

on:
  push:
    branches: [ main ]
env:
  AWS_ROLE_DEV: "arn:aws:iam::245446168277:role/enga-dor-github-actions-role-dev"
  AWS_DEFAULT_REGION: "eu-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  docker-push:
    runs-on: ubuntu-20.04
   
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_DEV }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t 245446168277.dkr.ecr.eu-central-1.amazonaws.com/dor-hackathon:${{ env.IMAGE_TAG }} .
          docker push 245446168277.dkr.ecr.eu-central-1.amazonaws.com/dor-hackathon:${{ env.IMAGE_TAG }}
          
      - name: Update Service
        run: |
          aws ecs update-service --region eu-central-1 --cluster arn:aws:ecs:eu-central-1:245446168277:cluster/enga-services-dev-ecs --service enga-dor-hackathon-service --force-new-deployment
